chore: update closed xml include .net 8 to target fw
ClosedXML/ClosedXML.Report pull request #344
Opened 2024-02-01 12:22 UTC by smakaiberriesandco

https://github.com/ClosedXML/ClosedXML.Report/issues/338
https://github.com/ClosedXML/ClosedXML.Report/issues/343

2024-02-02 13:37 UTC, smakaiberriesandco commented
when generating excel from a template with an empty list it throws an exception: `ClosedXML.Excel.Exceptions.EmptyTableException: Table 'Table1' should have at least 1 row.`

I updated the commit to fix that issue too.

2024-02-12 12:45 UTC, Pankraty requested changes

2024-02-12 12:45 UTC, Pankraty commented on ClosedXML.Report/ClosedXML.Report.csproj
> +    <TargetFrameworks>netstandard2.0;netstandard2.1;net8.0</TargetFrameworks>
Why do we need to add another target framework if it works fine with `nestandard2.1`?

2024-02-12 12:45 UTC, Pankraty commented on tests/ClosedXML.Report.Tests/RangeInterpreterTests.cs
>          public void ShouldDestroyEmptyTable()
The test is broken now

2024-02-14 12:22 UTC, smakaiberriesandco commented
Apologies for any confusion caused earlier (The exception mentioned above occurs only when the table range is one row larger than the row containing the placeholders). 

So when table range is correct and we provide an empty list to the table, the results still display the placeholders:
![image](https://github.com/ClosedXML/ClosedXML.Report/assets/93780795/5a5ee12a-af85-461b-932b-d063e577beac)
With my modifications, the table rows are now cleared:
![image](https://github.com/ClosedXML/ClosedXML.Report/assets/93780795/ee20b6e2-a2a4-43df-ba06-93d2ebbbcc19)
Test created, All tests have been successfully executed.

2024-03-06 14:00 UTC, smakaiberriesandco commented on tests/ClosedXML.Report.Tests/RangeInterpreterTests.cs
>          public void ShouldDestroyEmptyTable()
fixed

2024-04-11 06:36 UTC, merged

2024-04-11 06:37 UTC, Pankraty commented
Thanks for the contribution and sorry it took me so long!